Domain = "GLOBAL.ortelius.saas"
Application = "${Domain}.ortelius"
Application_Version = "10.0.0"

Name = "${Domain}.${COMPNAME}"
Variant = "${GIT_BRANCH}"
Version = "${IMAGE_VERSION}"
DockerRepo = "quay.io/ortelius/ms-dep-pkg-r"
DockerTag = "main-v10.0.444-g175c1d"

[Attributes]
     ServiceOwner = "${Domain}.ortelius"
     DiscordChannel = "https://discord.com/channels/722468819091849316/736611613485826150"
